env:
  es2021: true
  node: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - '@typescript-eslint'
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
  space-unary-ops:
    - error
    - words: true
      nonwords: false
      overrides:
        typeof: false
  keyword-spacing:
    - error
    - overrides:
        typeof:
          after: false
        if:
          after: false
        for:
          after: false
        while:
          after: false
        catch:
          after: false
        switch:
          after: false
  space-before-function-paren:
    - error
    - anonymous: 'never'
      named: 'never'
      asyncArrow: 'always'
